
import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const getBookDetailScreenStyles = (colorScheme: 'light' | 'dark') => {
  const colors = Colors[colorScheme];

  return StyleSheet.create({
    container: {
      backgroundColor: colors.background,
      paddingBottom: 60,
    },
    centered: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    coverWrap: {
      alignItems: 'center',
      paddingVertical: 24,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.lightGray,
    },
    cover: {
      width: 180,
      height: 260,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    coverPlaceholder: { backgroundColor: colors.lightGray },
    coverOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colorScheme === 'light' ? 'rgba(255, 250, 240, 0.05)' : 'rgba(0, 0, 0, 0.1)',
      borderRadius: 8,
    },
    card: {
      backgroundColor: colors.card,
      margin: 16,
      borderRadius: 12,
      padding: 16,
      marginTop: -10,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    title: {
      fontSize: 22,
      fontFamily: 'Pretendard-SemiBold',
      marginBottom: 4,
      color: colors.text,
    },
    meta: { color: colors.darkGray, marginBottom: 16, fontFamily: 'NotoSerifKR-Regular' },
    section: { marginTop: 16, backgroundColor: colors.card },
    sectionTitle: {
      fontSize: 18,
      fontFamily: 'Pretendard-SemiBold',
      marginBottom: 8,
      color: colors.text,
    },
    description: { lineHeight: 22, color: colors.text, fontFamily: 'NotoSerifKR-Regular' },
    descriptionToggle: {
      marginTop: 8,
      alignSelf: 'flex-end',
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    descriptionToggleText: {
      fontSize: 13,
      color: colors.primary,
      fontFamily: 'Pretendard-SemiBold',
    },
    editionsItem: {
      backgroundColor: colors.background,
      padding: 12,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    editionTitle: {
      fontSize: 16,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.primary,
    },
    editionMeta: {
      fontSize: 12,
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      marginTop: 4,
    },
    addToLibraryContainer: {
      marginTop: 20,
      marginHorizontal: 16,
      marginBottom: 20,
      alignItems: 'center',
    },
    addToLibraryButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      width: '80%',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    addToLibraryButtonText: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontSize: 16,
      fontFamily: 'Pretendard-SemiBold',
    },
    statusPickerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '100%',
      paddingHorizontal: 16,
      marginTop: 10,
      flexWrap: 'wrap',
    },
    statusOptionButton: {
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
      margin: 5,
      backgroundColor: colors.card,
    },
    statusOptionButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    statusOptionButtonText: {
      color: colors.text,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 14,
    },
    statusOptionButtonTextActive: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
    },
    cancelButton: {
      marginTop: 10,
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.darkGray,
      backgroundColor: colors.background,
    },
    cancelButtonText: {
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 14,
    },
    reviewSection: {
      paddingHorizontal: 16,
      marginTop: 16,
      paddingBottom: 20,
    },
    reviewSectionTitle: {
      fontSize: 17,
      fontFamily: 'Pretendard-SemiBold',
      marginBottom: 8,
      color: colors.text,
    },
    sortContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginBottom: 16,
    },
    sortButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
      marginLeft: 8,
    },
    sortButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    sortButtonText: {
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
    },
    sortButtonTextActive: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontFamily: 'Pretendard-SemiBold',
    },
  reviewInputContainer: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginTop: 16,
      marginBottom: 40,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    editingBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 14,
      marginBottom: 12,
    },
    editingBannerText: {
      color: colors.primary,
      fontFamily: 'NotoSerifKR-Regular',
    },
    cancelEditButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 6,
      backgroundColor: colorScheme === 'light' ? '#fff4ef' : '#2a1c16',
    },
    cancelEditButtonText: {
      color: colors.primary,
      fontFamily: 'Pretendard-SemiBold',
    },
    reviewInput: {
      borderWidth: 0,
      padding: 12,
      minHeight: 120,
      maxHeight: 200,
      textAlignVertical: 'top',
      backgroundColor: colors.background,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.text,
    },
    reviewInputScrollWrapper: {
      maxHeight: 200,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.lightGray,
      backgroundColor: colors.background,
      marginBottom: 8,
    },
    ratingContainer: {
      flexDirection: 'row',
      marginTop: 16,
      marginBottom: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    ratingWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
    },
    ratingTouchArea: {
      paddingHorizontal: 6,
      paddingVertical: 4,
    },
    starEmpty: {
      fontSize: 28,
      color: colors.lightGray,
      marginHorizontal: 6,
      lineHeight: 34,
    },
    starFilled: {
      fontSize: 28,
      color: colors.accent,
      marginHorizontal: 6,
      lineHeight: 34,
    },
    submitButton: {
      backgroundColor: colors.primary,
      padding: 14,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 10,
    },
    reviewCharCount: {
      textAlign: 'right',
      fontSize: 12,
      color: colors.darkGray,
      marginTop: 4,
      fontFamily: 'NotoSerifKR-Regular',
    },
    submitButtonText: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontFamily: 'Pretendard-SemiBold',
      fontSize: 16,
    },
    loginPrompt: {
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      textAlign: 'center',
      marginVertical: 20,
      padding: 16,
      backgroundColor: colors.card,
      borderRadius: 8,
    },
    reviewItem: {
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 14,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    reviewItemOwn: {
      borderColor: colors.primary,
    },
    reviewHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    reviewHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginTop: 24,
      marginBottom: 8,
    },
    reviewAuthor: {
      fontFamily: 'Pretendard-SemiBold',
      fontSize: 16,
      color: colors.text,
    },
    reviewRating: {
      color: colors.accent,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 14,
    },
    reviewCommentText: {
      lineHeight: 22,
      color: colors.text,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 14,
    },
    reviewFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.lightGray,
      paddingTop: 8,
    },
    reviewDate: {
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 12,
    },
    likeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: colors.background,
    },
    likeText: {
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      fontSize: 13,
    },
    likeTextLiked: {
      color: colors.primary,
      fontFamily: 'Pretendard-SemiBold',
      fontWeight: '600',
    },
    noReviews: {
      textAlign: 'center',
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      marginTop: 10,
      marginBottom: 20,
      fontSize: 14,
    },
  });
};
