
import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const getMyLibraryScreenStyles = (colorScheme: 'light' | 'dark') => {
  const colors = Colors[colorScheme];

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      padding: 20,
    },
    headerTitle: {
      fontSize: 24,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
      marginBottom: 24,
      marginTop: 60,
    },
    profileSection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 20,
      alignItems: 'center',
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    greeting: {
      fontSize: 22,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
    },
    email: {
      fontSize: 16,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      marginTop: 8,
      marginBottom: 24,
    },
    logoutButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      paddingHorizontal: 30,
      borderRadius: 8,
    },
    logoutButtonText: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontSize: 16,
      fontFamily: 'Pretendard-SemiBold',
    },
    loginPrompt: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    loginPromptText: {
      fontSize: 18,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      marginBottom: 20,
    },
    loginButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      paddingHorizontal: 30,
      borderRadius: 8,
    },
    loginButtonText: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontSize: 16,
      fontFamily: 'Pretendard-SemiBold',
    },
    summaryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingVertical: 15,
      marginHorizontal: 5,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    summaryItem: {
      alignItems: 'center',
      paddingHorizontal: 10,
    },
    summaryCount: {
      fontSize: 20,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.primary,
      marginTop: 6,
    },
    summaryLabel: {
      fontSize: 14,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      marginTop: 5,
    },
    summaryIcon: {
      color: colors.primary,
      marginBottom: 5,
    },
    myReviewsSummaryCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingVertical: 15,
      marginHorizontal: 5,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
      alignItems: 'center',
      justifyContent: 'center',
    },
    myReviewsSummaryIcon: {
      color: colors.primary,
      marginBottom: 5,
    },
    myReviewsSummaryCount: {
      fontSize: 20,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.primary,
      marginTop: 4,
    },
    myReviewsSummaryLabel: {
      fontSize: 14,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      marginTop: 5,
    },
    recentReviewsSection: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 15,
      marginHorizontal: 5,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    recentReviewsTitle: {
      fontSize: 18,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
      marginBottom: 10,
    },
    recentReviewsListContent: {
      paddingVertical: 5,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    modalContent: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 20,
      width: '90%',
      maxHeight: '80%',
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    modalTitle: {
      fontSize: 22,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
      marginBottom: 15,
      textAlign: 'center',
    },
    modalBookListContent: {
      paddingVertical: 10,
    },
    modalReviewListContent: {
      paddingVertical: 10,
    },
    modalCloseButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 20,
    },
    modalCloseButtonText: {
      color: colorScheme === 'light' ? '#fff' : colors.text,
      fontSize: 16,
      fontFamily: 'Pretendard-SemiBold',
    },
    bookItemContainer: {
      width: '48%',
      margin: '1%',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 10,
      borderWidth: 1,
      borderColor: colors.lightGray,
    },
    bookThumbnail: {
      width: 100,
      height: 150,
      borderRadius: 8,
      backgroundColor: colors.lightGray,
      marginBottom: 8,
    },
    bookThumbnailOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colorScheme === 'light' ? 'rgba(255, 250, 240, 0.05)' : 'rgba(0, 0, 0, 0.1)',
      borderRadius: 8,
    },
    bookInfoContainer: {
      alignItems: 'center',
    },
    bookTitle: {
      fontSize: 13,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
      textAlign: 'center',
      lineHeight: 18,
      marginBottom: 4,
    },
    bookAuthor: {
      fontSize: 11,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      textAlign: 'center',
    },
    reviewItemContainer: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderRadius: 10,
      padding: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.lightGray,
      alignItems: 'center',
    },
    reviewBookThumbnail: {
      width: 60,
      height: 90,
      borderRadius: 5,
      backgroundColor: colors.lightGray,
      marginRight: 10,
    },
    reviewBookThumbnailOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colorScheme === 'light' ? 'rgba(255, 250, 240, 0.05)' : 'rgba(0, 0, 0, 0.1)',
      borderRadius: 5,
    },
    reviewInfoContainer: {
      flex: 1,
    },
    reviewItemTitle: {
      fontSize: 15,
      fontFamily: 'Pretendard-SemiBold',
      color: colors.text,
      marginBottom: 2,
    },
    reviewItemRating: {
      fontSize: 12,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.accent,
      marginBottom: 5,
    },
    reviewItemComment: {
      fontSize: 12,
      fontFamily: 'NotoSerifKR-Regular',
      color: colors.darkGray,
      lineHeight: 16,
    },
    loadingText: {
      textAlign: 'center',
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      marginTop: 10,
    },
    errorText: {
      textAlign: 'center',
      color: 'red',
      fontFamily: 'NotoSerifKR-Regular',
      marginTop: 10,
    },
    emptySectionText: {
      textAlign: 'center',
      color: colors.darkGray,
      fontFamily: 'NotoSerifKR-Regular',
      marginTop: 10,
    },
  });
};
