import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
    padding: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
    marginBottom: 30,
    marginTop: 40,
  },
  profileSection: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
  },
  greeting: {
    fontSize: 22,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
  },
  email: {
    fontSize: 16,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    marginTop: 8,
    marginBottom: 24,
  },
  logoutButton: {
    backgroundColor: Colors.light.primary,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Pretendard-SemiBold',
  },
  loginPrompt: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginPromptText: {
    fontSize: 18,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    marginBottom: 20,
  },
  loginButton: {
    backgroundColor: Colors.light.primary,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Pretendard-SemiBold',
  },
  summaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    paddingVertical: 15,
    marginHorizontal: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
  },
  summaryItem: {
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  summaryCount: {
    fontSize: 24,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.primary,
  },
  summaryLabel: {
    fontSize: 14,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    marginTop: 5,
  },
  summaryIcon: {
    color: Colors.light.primary,
    marginBottom: 5,
  },
  myReviewsSummaryCard: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    paddingVertical: 15,
    marginHorizontal: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
  },
  myReviewsSummaryIcon: {
    color: Colors.light.primary,
    marginBottom: 5,
  },
  myReviewsSummaryCount: {
    fontSize: 24,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.primary,
  },
  myReviewsSummaryLabel: {
    fontSize: 14,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    marginTop: 5,
  },
  recentReviewsSection: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
  },
  recentReviewsTitle: {
    fontSize: 18,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
    marginBottom: 10,
  },
  recentReviewsListContent: {
    paddingVertical: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: Colors.light.background,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
    marginBottom: 15,
    textAlign: 'center',
  },
  modalBookListContent: {
    paddingVertical: 10,
  },
  modalReviewListContent: {
    paddingVertical: 10,
  },
  modalCloseButton: {
    backgroundColor: Colors.light.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  modalCloseButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Pretendard-SemiBold',
  },
  bookItemContainer: {
    width: '48%',
    margin: '1%',
    alignItems: 'center',
    backgroundColor: Colors.light.card,
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
  },
  bookThumbnail: {
    width: 100,
    height: 150,
    borderRadius: 8,
    backgroundColor: Colors.light.lightGray,
    marginBottom: 8,
  },
  bookThumbnailOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 250, 240, 0.05)',
    borderRadius: 8,
  },
  bookInfoContainer: {
    alignItems: 'center',
  },
  bookTitle: {
    fontSize: 13,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 4,
  },
  bookAuthor: {
    fontSize: 11,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    textAlign: 'center',
  },
  reviewItemContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.light.card,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.light.lightGray,
    alignItems: 'center',
  },
  reviewBookThumbnail: {
    width: 60,
    height: 90,
    borderRadius: 5,
    backgroundColor: Colors.light.lightGray,
    marginRight: 10,
  },
  reviewBookThumbnailOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 250, 240, 0.05)',
    borderRadius: 5,
  },
  reviewInfoContainer: {
    flex: 1,
  },
  reviewItemTitle: {
    fontSize: 15,
    fontFamily: 'Pretendard-SemiBold',
    color: Colors.light.text,
    marginBottom: 2,
  },
  reviewItemRating: {
    fontSize: 12,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.accent,
    marginBottom: 5,
  },
  reviewItemComment: {
    fontSize: 12,
    fontFamily: 'NotoSerifKR-Regular',
    color: Colors.light.darkGray,
    lineHeight: 16,
  },
  loadingText: {
    textAlign: 'center',
    color: Colors.light.darkGray,
    fontFamily: 'NotoSerifKR-Regular',
    marginTop: 10,
  },
  errorText: {
    textAlign: 'center',
    color: 'red',
    fontFamily: 'NotoSerifKR-Regular',
    marginTop: 10,
  },
  emptySectionText: {
    textAlign: 'center',
    color: Colors.light.darkGray,
    fontFamily: 'NotoSerifKR-Regular',
    marginTop: 10,
  },
});
